#!/bin/bash
#$ -M smondal@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -l h_rt=24:00:00
#$ -pe smp 4
#$ -N sig_train
#$ -o /users/smondal/signature-project/logs/sig_train.$JOB_ID.out
#$ -e /users/smondal/signature-project/logs/sig_train.$JOB_ID.err

source ~/.bashrc
conda activate machine-learning

cd /users/smondal/signature-project/repo
export SIGNATURE_DATA_ROOT=/users/smondal/signature-project/data/cedar-bhsig260

python -m signature_siamese.train
